### PR TITLE
Use `*_js` instead of `*_helper` for EM_JS functions

### PR DESCRIPTION
**Pull request by kleisauke**
See: https://github.com/hoodmane/libffi-emscripten/pull/20#discussion_r1058896255.

### CODE REVIEW

**Comment by kleisauke** [comment]
It's great to see that the `test-dejagnu*` suites almost passes on the master branch!

It seems that the remaining failures are due to initial generation of symbol lists cache (introduced in commit https://github.com/emscripten-core/emscripten/commit/3e1b8387691d742a6bc34e19bc5655f51d55a0f0), causing a timeout. Perhaps we could increase this timeout in DejaGnu somehow?

**Comment by kleisauke** [comment]
> causing a timeout

Ah, my assumption was wrong. This is due to https://github.com/emscripten-core/emscripten/issues/18607, sorry for the noise.

**Comment by hoodmane** [comment]
Thanks @kleisauke!

**Comment by hoodmane** [comment]
By the way I added you to the copyright notice:
https://github.com/hoodmane/libffi-emscripten/commit/e2f8291ab03c351347a0b4d1e992e125b42a31a4
Hope that's okay with you.

**Comment by kleisauke** [comment]
It's fine for me, although you did most of the work. :)

**Pull request merged**
